name: optician_desktop_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  drift: ^2.28.1
  path_provider: ^2.1.5
  sqlite3: ^2.8.0
  fluttertoast: ^8.2.8
  sqlite3_flutter_libs: ^0.5.39
  image_picker: ^1.1.2
  file_picker: ^10.2.3
  window_size: ^0.1.0
  permission_handler: ^12.0.1
  flutter_thermal_printer: ^1.1.0
  shared_preferences: ^2.5.3
  printing: ^5.14.2
  barcode_widget: ^2.0.4
  esc_pos_utils_plus: ^2.0.4
  print_bluetooth_thermal: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  drift_dev: ^2.28.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: FontMain
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700